### ISSUE TITLE
Padding Issue

### ISSUE THREAD

**Issue by patelakshay13890** [bmelnychuk/AndroidTreeView#1]
No Space as in Image for Folder Structure before icon...

**Comment by bmelnychuk** [comment]
There is no style applied by default. I guess you should use `tView.setDefaultContainerStyle(R.style.TreeNodeStyle);`
or take a look at `FolderStructureFragment.java` as example from demo app.

**Comment by bmelnychuk** [comment]
Did you manage to resolve it. Can I close this issue?

**Comment by pcombeaud** [comment]
It seems this issue depends on Android version.
Running the sample on Android 5.0 everything is OK.
But on previous versions (4.4, 4.0) style is not applied to the treeView.

**Comment by bmelnychuk** [comment]
Should be fixed

**Comment by pcombeaud** [comment]
It works fine
Thx
