### ISSUE TITLE
Child Nodes Left Margin and setDisplayHomeAsUpEnabled not working

### ISSUE THREAD

**Issue by joaocorreia00** [bmelnychuk/AndroidTreeView#10]
I implemented the library on my android app, but i have 2 problems:
- The child nodes doesn't have any left margin, so the tree looks like a simple list of itens.
- And setDisplayHomeAsUpEnabled isnt working in the TreeNode fragment.

This happened to someone ?

**Comment by bmelnychuk** [comment]
There is similar issue with padding for android 4 (if Im not mistaken).
I don't think that treeView can disable setDisplayHomeAsUpEnabled functionality. Does it work if you remove treeView from fragment?

**Comment by joaocorreia00** [comment]
Just tried setDisplayHomeAsUpEnabled with treeView and still not work, probably not related.
About the padding issue, Is there a workaround for it?

**Comment by joaocorreia00** [comment]
UPDATE:
If setDisplayHomeAsUpEnabled doesn't work on the TreeView Fragment do this on onOptionsItemSelected method:
public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.expandAll:
                tView.expandAll();
                break;

            case R.id.collapseAll:
                tView.collapseAll();
                break;
            case android.R.id.home:
                NavUtils.navigateUpFromSameTask(getActivity()); /* this is do the same as setDisplayHomeAsUpEnabled */
                return true;
        }
        return true;
    }

**Comment by joaocorreia00** [comment]
UPDATE:
if setDisplayHomeAsUpEnabled doens't in the fragment treeview do this on onOptionsItemSelected:

public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.expandAll:
                tView.expandAll();
                break;
            case R.id.collapseAll:
                tView.collapseAll();
                break;
            case android.R.id.home:
                NavUtils.navigateUpFromSameTask(getActivity()); /* IMPORTANT PART HERE*/
                return true;
        }
        return true;
    }

**Comment by bmelnychuk** [comment]
Padding issue should be fixed with latest changes
