### ISSUE TITLE
Child node layout doesn't leave a gap on the left.

### ISSUE THREAD

**Issue by adamhongmy** [bmelnychuk/AndroidTreeView#101]
Right now, my tree view looks like a normal list. The children don't move to the left.
I had compared the project's sample but there isn't any different. What am I missing?

**Comment by LukasJue** [comment]
You can use the paddingLeft atrribute to force such an Gap. I had this issue once too, but I can't reproduce it currently.

**Comment by adamhongmy** [comment]
Ya I gave up and just add padding on the layout and using "if(node.isLeaf())". I don't understand how the sample project did it.

**Comment by markfili** [comment]
this problem still exists, using version 1.2.9.

**Comment by IHNEL** [comment]
I don't understand how the author draw file structure with padding (screenshots).

**Comment by bkhong87** [comment]
For your info...

tView.setDefaultContainerStyle(R.style.TreeNodeStyleCustom);

<style name="TreeNodeStyleCustom">
        <item name="android:paddingLeft">20dp</item>
 </style>

**Comment by ugurcany** [comment]
As a solution, I added the following code inside `createNodeView` method of my custom node viewholder to add correct left paddings to child nodes according to their levels:

```
int treeviewPadding = ResourcesUtil.getDimensionPixelSize(R.dimen.treeview_padding);
view.setPadding(node.getLevel() * treeviewPadding, treeviewPadding, treeviewPadding, treeviewPadding);
```
