### ISSUE TITLE
Listner for Expansing & Collapsing

### ISSUE THREAD

**Issue by patelakshay13890** [bmelnychuk/AndroidTreeView#12]
How can we have Listener or method for checking weather Node is Expanded Or Collapsed ??
Or can we have Listener for that ??
And then How can I add dynamically Add Node & remove all those added node on Collapsing Node ??

**Comment by abluescarab** [comment]
I know your issue is really old, but I thought I'd let you know anyway: in your custom TreeNode holder, you can override the method "toggle", which has a boolean value as a parameter that indicates whether the node was expanded (true) or collapsed (false).

The method in question:

    public class CustomTreeNodeHolder extends TreeNode.BaseNodeViewHolder<CustomTreeItem> {
        ...
        @Override
        public void toggle(boolean active) {
            if(active) {
                // the node is expanded
            }
            else {
                // the node is collapsed
            }
        }
        ...
    }
