### ISSUE TITLE
How i can expand node with all parents?

### ISSUE THREAD

**Issue by terrakok** [bmelnychuk/AndroidTreeView#128]
I did not find such a method in the library

**Comment by terrakok** [comment]
And how i can expand node with all parents?

**Comment by terrakok** [comment]
I did it this way:

```kotlin
private fun expandNodeBranch(treeNode: TreeNode, expand: Boolean = false) {
  if (expand && !treeNode.isLeaf) androidTree?.expandNode(treeNode)
  if (treeNode.level > 0) expandNodeBranch(treeNode.parent, true)
}
```

and call for any node: `expandNodeBranch(node)`

**Comment by alierdogan7** [comment]
> ```kotlin
> private fun expandNodeBranch(treeNode: TreeNode, expand: Boolean = false) {
>   if (expand && !treeNode.isLeaf) androidTree?.expandNode(treeNode)
>   if (treeNode.level > 0) expandNodeBranch(treeNode.parent, true)
> }
> ```

this really works. JazakAllah !
