### ISSUE TITLE
Implement selectable background

### ISSUE THREAD

**Issue by testica** [bmelnychuk/AndroidTreeView#13]
I need to display a background when I select a node like select element of ``ListView``, I'm trying to set a background in ``nodeClickListener`` but doesn't work, any way to solve this? Thanks.

**Comment by bmelnychuk** [comment]
Will take a look on it this weekend

**Comment by bmelnychuk** [comment]
Is this something similar you are trying to achieve?

![Screenshot](https://drive.google.com/uc?id=0B3hs6EXn55WUdDctRXcyRElLS1E&authuser=0)

**Comment by testica** [comment]
Not exactly, I call "select" when I click over a node, and its background is changed and then its disappear automatically after stop pressing, something like when a item of standard ListView is pressed (animation). It's a way to know what node I press. Thanks

**Comment by bmelnychuk** [comment]
Could you check latest commit, the demo app

**Comment by testica** [comment]
Thanks!

**Comment by MatthewGitter** [comment]
Great library, well structured.

In the FolderStructureFragment type of tree, I need the background of the "Last Clicked" node to remain "gray" the way it turns when first clicked (and also while held), indicating it is the last clicked node, even when the click is released. Instead the background returns to normal (white/transparent) when the click is released. I can't even find in the library code where the background is set to gray when the node is clicked. Thanks for the insights.
