### ISSUE TITLE
No way to change root node

### ISSUE THREAD

**Issue by Diomas** [bmelnychuk/AndroidTreeView#17]
Hello, I can't find a way to change the root node (replace the whole tree). How can this be achieved?

**Comment by bmelnychuk** [comment]
Maybe you can just create another tree and clear container layout.

**Comment by Diomas** [comment]
Seems replacing direct root children doesn't have any effect, so recreating the view is the only way.

**Comment by LiuJQ** [comment]
Maybe it's the only way for version 1.28 on jcenter, but someone had found another solution. As below
[added removeAllNodes method to clear root.](https://github.com/bmelnychuk/AndroidTreeView/commit/b66babb9e05d4ca91c02963588df1ec1eb4d17d5)
Why not just update this code and the jar on jcenter ?
