### ISSUE TITLE
Dynamic Add/Remove Node

### ISSUE THREAD

**Issue by patelakshay13890** [bmelnychuk/AndroidTreeView#2]
I need dynamic creation of Nodes on Expanding the Parent..
So how can i achieve this ?

**Comment by bmelnychuk** [comment]
Dynamic add/remove is not supported yet. That is something I have in mind and will be implemented soon. There is 'Upcoming changes' at the end of readme.md and is it listed there, stay tuned. 
Thank you!

**Comment by patelakshay13890** [comment]
Sure & thanx for quick response

**Comment by bmelnychuk** [comment]
You can try demo app (1.2.0) there is an example how to add/remove nodes. Does it solve your problem?

**Comment by patelakshay13890** [comment]
Can we have Listener for Expanding & Collapsing Event on Nodes with
Multi-level ???

**Comment by bmelnychuk** [comment]
Check out latest version. You have node click listener `TreeNode.setClickListener(..)` and its only method
`void onClick(TreeNode clickedNode, Object value)`
There you can check wheather `clickedNode.isExpanded`
and add its subnodes

**Comment by indrac** [comment]
Thanks for share this library.
But I have one question. How to use this tree view for parsing Json that have parent and children and so on?
Regards.

**Comment by bmelnychuk** [comment]
You can parse Json by your self (or use library for that) and then create TreeNode structure. This is data manipulation operations, when this library is rather for displaying, but I will think about it. 
Thanks!

**Comment by indrac** [comment]
Yup, for parsing json I use volley library. Is it possible if I collaborate this volley with your treeview library?

**Comment by bmelnychuk** [comment]
You can parse json in model you want, then you should write code to convert that model into TreeNode model and then you can display it.

**Comment by DottiL** [comment]
Hello, I'm currently using your treeView to show files and folder content. I need to be able to add and remove nodes depending on what the user want to do (open a file/folder or remove a currently open file/folder). Is it possible to "refresh" the AndroidTreeView? I mean whenever the user want to add a file, I just create a node and add it to the root for example, then I need to report this update to the view and show the changes (that will be just the new node added). 
Thanky you very much and thumbs up for this project

**Comment by bmelnychuk** [comment]
I think you can pass your custom listener to your ViewHolder implementation. For example `IconTreeItemHolder` from demo app:
```java
 public class IconTreeItemHolder ..... {
    .....
    public interface AddNodeListener {
         void onNodeAdded(TreeNode node);
    }
    private AddNodeListener addNodeListener;
    public void setAddNodeListener(AddNodeListener listener) {

}
```

**Comment by DottiL** [comment]
Hello thank you very much. I will try soon.

**Comment by DottiL** [comment]
I think you missunderstand me. What I do is this:

private void addFileRecursive(DropboxFile dbFile, TreeNode parent) {
        if(!dbFile.getFileInfo().isFolder) {
            TreeNode child = new TreeNode(dbFile.getFileInfo().path.getName());
            parent.addChild(child);
        } else {
            TreeNode child = new TreeNode(dbFile.getFileInfo().path.getName());
            parent.addChild(child);

            List<DbxFileInfo> folderContent = null;
            try {
                folderContent = dbManager.getFileSystemByAccount(dbFile.getAccount()).listFolder(dbFile.getFileInfo().path);
            } catch (DbxException e) {
                e.printStackTrace();
            }

            for(DbxFileInfo info: folderContent) {
                addFileRecursive(new DropboxFile(info, dbFile.getAccount()), child);
            }
        }
    }

Then I have a public function addFile that will call this recursive function.  This public function is called  by another object whenever a new file must be added. In the posted code, I just add to my tree the new node, but now I need to "show" the new file in the tree view. I'm wondering if there is a function like refreshView() that will show the new added nodes. What I tried was to create a new AndroidTrewwView and pass the root with the new added nodes, but this does not seems to work (I got an exception: "The specified child has already a parent", when I try to add the new view with container.addView(AndroidTreeView.getView())). Thank you

**Comment by bmelnychuk** [comment]
Have you tried `treeView.addNode(parent, newChild);` ?

**Comment by DottiL** [comment]
Nope I try now

**Comment by DottiL** [comment]
AHH now its working. Thank you very much!

**Comment by DottiL** [comment]
Didnt see this method

**Comment by bmelnychuk** [comment]
Check out sample app there is an example with add/delete operation

**Comment by DottiL** [comment]
Yep thank you. Another quesiton, I saw in the images on github that you added lines between the files. Did you do it by custom views?

**Comment by DottiL** [comment]
Ok yes achieved it by views. Thank you very much

**Comment by DottiL** [comment]
Hello, I have another question. Is it possible to add an onLongClickListener?

**Comment by DottiL** [comment]
I mean not from the holder, but from the object that is creating the TreeView

**Comment by bmelnychuk** [comment]
It is not supported yet, i think I will add this soon. Partially this can be implemented in custom holder, what are you trying to achieve?

**Comment by DottiL** [comment]
Hello, actually Im trying to create a context menu on long click on each node. In this way I can remove/save/create (for example create a file in a folder held in the treeview) files and folder.

**Comment by dun74fr** [comment]
Hello bmelnychuk,
I'd like to implement the listener pattern you exposed in this issue.
"I think you can pass your custom listener to your ViewHolder implementation"
In the ViewHolder I do not have any problem but how can I pass the listener from my Fragment where I create the TreeView.
The only reference between tView and the ViewHolder is tView.setDefaultViewHolder(IconTreeItemHolder.class);
How can I call the set  setAddNodeListener() ?
Thanks

**Comment by bmelnychuk** [comment]
Yeaaahh, I am afraid I don't have solution with custom listener and setDefaultViewHolder() :( 
I will take a look on it this weekend

**Comment by dun74fr** [comment]
Ok thanks,
and is it possible to refresh the tree ? In my app I let a user move a leaf from one folder to another.
I try to update the tree like this : 
```java
getTreeView().removeNode(node);
TreeNode newTalk = new TreeNode(...);
getTreeView().addNode(((FolderDialog) dialog).selectedNode, newTalk);
```
The remove is done but the add in another parent of the tree does not appear.

**Comment by bmelnychuk** [comment]
@dun74fr  This code looks good.
Could you share your classes so I can try it

**Comment by dun74fr** [comment]
Sorry, As commented in my EDIT it was my fault. I was selecting a node in a popup tree and trying to use it in another tree so the reference was not found.
