### ISSUE TITLE
Same TreeNode ID issue when deleting and inserting nodes

### ISSUE THREAD

**Issue by Lobi123** [bmelnychuk/AndroidTreeView#20]
Let's say my root node has three children.
N1: id 0, N2: id 1, N3: id 2
I delete N2 from the tree view, but afterwards N3 still has id 2.
N1: id 0,  N3: id 2
Now when I insert a new TreeNode N4, it will be given id 2.
N1: id 0,  N3: id 2, N4: id 2

**Comment by bmelnychuk** [comment]
Thanks for posting! Yes I had that in mind, will try to fix it in nearest future

**Comment by MathiasBerwig** [comment]
I created a simple implementation to generate new ids. What do you think, @bmelnychuk?
```java
private int mLastId;
private int generateId() { return ++mLastId; }
public TreeNode addChild(TreeNode childNode) {
        ...
        childNode.mId = generateId();
        ... 
}
```
