### ISSUE TITLE
Crash when nodes more than 7 level

### ISSUE THREAD

**Issue by Alffrredo** [bmelnychuk/AndroidTreeView#22]
In Folder Structure Example application when nodes get more than 7 level app will crash.

**Comment by bmelnychuk** [comment]
Well, app is not crashing on my side (see screenshots in readme). What android version are you using?

**Comment by Alffrredo** [comment]
Galaxy Tab2, Android 4.0.3

07-07 00:02:16.975: E/AndroidRuntime(29028): FATAL EXCEPTION: main
07-07 00:02:16.975: E/AndroidRuntime(29028): java.lang.StackOverflowError
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:38)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.GLES20RecordingCanvas$1.newInstance(GLES20RecordingCanvas.java:46)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.GLES20RecordingCanvas$1.newInstance(GLES20RecordingCanvas.java:44)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.util.FinitePool.acquire(FinitePool.java:69)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.util.SynchronizedPool.acquire(SynchronizedPool.java:39)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.GLES20RecordingCanvas.obtain(GLES20RecordingCanvas.java:66)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.GLES20DisplayList.start(GLES20DisplayList.java:52)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10443)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.draw(View.java:11028)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10464)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.getDisplayList(View.java:10462)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.view.View.draw(View.java:11028)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.widget.FrameLayout.draw(FrameLayout.java:450)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at android.widget.ScrollView.draw(ScrollView.java:1754)
07-07 00:02:16.975: E/AndroidRuntime(29028): 	at

**Comment by bmelnychuk** [comment]
If I remember correctly it's recommended to not have a layout deeper then 10 levels. And on previous versions of android (4.0 is pretty old one) it causes crash. As you can see on screenshot it does not crash on latest android version.

**Comment by lucassales2** [comment]
I think this crash is pretty serious, it should be at least on README.md that it wont work on those Android Versions. I understand that would be necessary to re-make a lot of the code, and its not the developers fault, but at least let people know that if they are developing apps compatible with those API levels they will have limitations

**Comment by bmelnychuk** [comment]
@lucassales2 Probably you are right, will do that

**Comment by muhammad-naderi** [comment]
also happens on 4.4.2
