### ISSUE TITLE
intention should will be default behavior

### ISSUE THREAD

**Issue by luoqii** [bmelnychuk/AndroidTreeView#23]
this project is cooool!
but first time, i can not know how to intent sub-item,
after search i see this:
		v.setDefaultContainerStyle(R.style.TreeNodeStyleCustom);
it works for me,
but i think this should be by default.

**Comment by bmelnychuk** [comment]
Funny thing is that other people convinced that it should not be by default. Well, maybe you are right) I did mention that in description and used that is samples.

**Comment by luoqii** [comment]
can we make this explicityly, maybe text it in README.md is a good choice.

Good luck.
