### ISSUE TITLE
How do you know in the Activity or Fragment when a checkbox has been checked?

### ISSUE THREAD

**Issue by surfer190** [bmelnychuk/AndroidTreeView#26]
How do you know in the Activity or Fragment when a checkbox has been checked?

**Comment by bmelnychuk** [comment]
Does AndroidTreeView .getSelected() work for you?

**Comment by surfer190** [comment]
@bmelnychuk yes it does, but I want to know in the activity or fragment when a check box / tree node becomes selected.

ie. Listen for selections

**Comment by bmelnychuk** [comment]
You can pass your custom listener to your holder from fragment or activity. Take a look at ```SelectableHeaderHolder.java``` from sample app 
You can try something like:
```
public class YourHolder {
    public interface CheckListener {
        void onCheck();
    }
    ...
    private CheckListener listener;
    ...
    // Should be called from fragment/activity
    public void setCheckListener(CheckListener listener) {
        this.listener = listener;
    }
    ....
    @Override
    public View createNodeView(final TreeNode node, IconTreeItemHolder.IconTreeItem value) {
        ....
        nodeSelector = (CheckBox) view.findViewById(R.id.node_selector);
        nodeSelector.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            listener.onCheck()
        }
    }
}
```

**Comment by surfer190** [comment]
@bmelnychuk 

Awesome...

I am having some difficulty with setting it though.

In `MyFragment.java`:

I can't use:

```
tView = new AndroidTreeView(getActivity(), root);
tView.setCheckListener(...);
```

I need a reference to the `viewholder`, which is only used when creating the nodes, so nodes must be created within the `fragment/activity`?

**Comment by bmelnychuk** [comment]
you should call setCheckListener for your holder but not AndroidTree view.
I can prepare simple demo for you this weekend

**Comment by surfer190** [comment]
@bmelnychuk Nevermind I have sorted it out as you described. It works like a charm.

I am struggling with [hiding nodes](https://github.com/bmelnychuk/AndroidTreeView/issues/28) now
