### ISSUE TITLE
Waiting for maven central

### ISSUE THREAD

**Issue by hamen** [bmelnychuk/AndroidTreeView#3]
Hi
You could use this
http://downright-amazed.blogspot.fr/2011/09/hosting-maven-repository-on-github-for.html
in the meantime ;)
Ivan

**Comment by bmelnychuk** [comment]
Hi Ivan, thank you! I will consider using that. 
Actually I'm waiting for response from Sonatype (it take up to 2 days). Maven central is my top priority issue

**Comment by bmelnychuk** [comment]
```compile 'com.github.bmelnychuk:atv:1.2.0'```
Thanks!
