### ISSUE TITLE
Remove the default listener and handle Node expansion manually

### ISSUE THREAD

**Issue by Odaym** [bmelnychuk/AndroidTreeView#31]
I have tried to do `treeView.setDefaultNodeClickListener(null);` and then do this code whenever I'm creating a new node:

```java
taskNode.setClickListener(new TreeNode.TreeNodeClickListener() {
            @Override
            public void onClick(TreeNode treeNode, Object o) {
                Intent openTaskDetails_Activity = new Intent(getActivity(), Task_ViewPager_Activity.class);
                openTaskDetails_Activity.putExtra(Constants.GOD_TASK_OBJECT, Parcels.wrap(parentTask));
                startActivity(openTaskDetails_Activity);
            }
        });
```
But when I do this, both actions happen; The node expands/collapses and the item opens in a new activity, how can I disable the default node listener so that I can let the arrow button on the far right of my layout be responsible for expanding and collapsing items?

**Comment by Odaym** [comment]
I would imagine that inside the adapter I can do:
```java
arrowImage.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                toggle(!treeNode.isExpanded());
            }
        });
```
but I first need to make sure that the default listener is dedicated is removed to guarantee both independent actions

**Comment by Odaym** [comment]
Actually no, inside the adapter I wrote the following and it works very well to handle the expanding/collapsing of the nodes:

```java
arrowImage.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (!treeNode.isExpanded()) {
                    (treeNode.getViewHolder().getTreeView()).expandNode(treeNode);
                    treeNode.setExpanded(true);
                } else {
                    (treeNode.getViewHolder().getTreeView()).collapseNode(treeNode);
                    treeNode.setExpanded(false);
                }
            }
        });
```
But how to shut off the default node click listener

**Comment by Odaym** [comment]
As a hack, I downloaded your project and imported it to use it in mine so that I could remove the `toggleNode(n);` at `line 250` of the AndroidTreeView.java class and I got what I wanted, thanks for writing it so neatly friend

**Comment by Ivolian** [comment]
@Odaym 
Cool !

**Comment by joaocorreia00** [comment]
@Odaym How do you imported to your project? As a module?

**Comment by Odaym** [comment]
@joaocorreia00 I actually took the files and placed them manually in my project first to see whether it would fix the issue first, it did. After that I just left them in the project and it's working fine

**Comment by joaocorreia00** [comment]
@Odaym Thank you, it worked.

**Comment by Odaym** [comment]
good job

**Comment by Summuss** [comment]
I disable the default clickListenr with  `treeView.setUseAutoToggle(false)`.
