### ISSUE TITLE
How to get name of selected nodes ?

### ISSUE THREAD

**Issue by marinica94** [bmelnychuk/AndroidTreeView#37]
How can I get the name of the selected nodes?

**Comment by bmelnychuk** [comment]
You can call AndroidTreeView.getSelected() to get List<TreeNode> of selected nodes. And then for each TreeNode you take value

**Comment by marinica94** [comment]
node.getValue() ? it returns an object ? How to proceed to the next step ?

**Comment by bmelnychuk** [comment]
It returns object you used to create the node.
P.s. We are talking about name that is your custom property right?

**Comment by marinica94** [comment]
TreeNode node = new TreeNode(new SelectableHeaderHolder.IconTreeItem(R.string.ic_folder, name)).setViewHolder(new SelectableHeaderHolder(getApplicationContext()));

We are talking about the name of the TextView in Holder :) The TextView that is used to show the directory name. thanks.

**Comment by bmelnychuk** [comment]
So in this case getValue() as described previously would return you SelectableHeaderHolder.IconTreeItem object, so you can cast it and get name

**Comment by marinica94** [comment]
I've tried but couldn't figure it out. I use IconTreeItem as an internal class as follow:

public class SelectableHeaderHolder extends TreeNode.BaseNodeViewHolder<SelectableHeaderHolder.IconTreeItem> {
    private TextView tvValue;
    private PrintView arrowView;
    private CheckBox nodeSelector;

    public SelectableHeaderHolder(Context context) {
        super(context);
    }

    @Override
    public View createNodeView(final TreeNode node, IconTreeItem value) {
        final LayoutInflater inflater = LayoutInflater.from(context);
        final View view = inflater.inflate(R.layout.layout_selectable_header, null, false);

        tvValue = (TextView) view.findViewById(R.id.node_value);
        tvValue.setText(value.text);

        final PrintView iconView = (PrintView) view.findViewById(R.id.icon);
        iconView.setIconText(context.getResources().getString(value.icon));

        arrowView = (PrintView) view.findViewById(R.id.arrow_icon);
        if (node.isLeaf()) {
            arrowView.setVisibility(View.GONE);
        }

        nodeSelector = (CheckBox) view.findViewById(R.id.node_selector);
        nodeSelector.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                node.setSelected(isChecked);
                for (TreeNode n : node.getChildren()) {
                    getTreeView().selectNode(n, isChecked);
                }
            }
        });
        nodeSelector.setChecked(node.isSelected());

        return view;
    }

    @Override
    public void toggle(boolean active) {
        arrowView.setIconText(context.getResources().getString(active ? R.string.ic_keyboard_arrow_down : R.string.ic_keyboard_arrow_right));
    }

    @Override
    public void toggleSelectionMode(boolean editModeEnabled) {
        nodeSelector.setVisibility(editModeEnabled ? View.VISIBLE : View.GONE);
        nodeSelector.setChecked(mNode.isSelected());
    }

    public String getText() {

        return tvValue.getText().toString();
    }

    public static class IconTreeItem {
        public int icon;
        public String text;

        public IconTreeItem(int icon, String text) {
            this.icon = icon;
            this.text = text;
        }

        public String getText() {
            return text;
        }
    }
}

**Comment by marinica94** [comment]
I have figured it out, thank you for your help :+1:

**Comment by jackspa** [comment]
how can you get the next of the node?
