### ISSUE TITLE
allowBackup:true set in Library?

### ISSUE THREAD

**Issue by dualbootsoftware** [bmelnychuk/AndroidTreeView#38]
Hi,

I'm running into a problem where my app has 

     <application android:allowBackup="false" tools:replace="allowBackup" />

There seems to be a Gradle/Android bug that causes that to fail because the AndroidTreeView Library has 

     <application android:allowBackup="true" /> 

Is there a reason this is set in the library manifest file itself? I was thinking maybe it wasn't necessary? 

Thanks for the great software!

**Comment by bmelnychuk** [comment]
Hi, it was auto-generated. I will remove it and upload new version today (or maybe tomorrow)

**Comment by dualbootsoftware** [comment]
Great, thank you!

**Comment by bmelnychuk** [comment]
version 1.2.7
