### ISSUE TITLE
Folder structure example

### ISSUE THREAD

**Issue by abhi98228** [bmelnychuk/AndroidTreeView#4]
When you expand the tree structure beyond some level it wont scroll horizontally. Only vertical scroll is working. How do I fix this

**Comment by bmelnychuk** [comment]
Unfortunately it is known bug, I'm still thinking about the solution.
Thank you for posting it!

**Comment by jixiang255** [comment]
I fix this problem by add HorizontalScrollView and this contain a LinearLayout

**Comment by bmelnychuk** [comment]
Guys, you check out my implementation, let me know if it works for you
