### ISSUE TITLE
Detect what part of a node has been clicked

### ISSUE THREAD

**Issue by abluescarab** [bmelnychuk/AndroidTreeView#45]
Is it possible to detect which part of a node has been clicked? I want to have an arrow on the left that expands the node and text to the right that opens a fragment when it's tapped.

**Comment by bmelnychuk** [comment]
Yes it is possible, just like selection mode, when checkbox is just selectable item, and the name would expand node

**Comment by abluescarab** [comment]
Cool, I got it! Thanks!

For anyone else wondering, here's mine:

    public class TreeNodeHolder extends TreeNode.BaseNodeViewHolder<TreeNodeHolder.PageTreeItem> {
        @Override
        public View createNodeView(TreeNode node, final PageTreeItem value) {
            final LayoutInflater inflater = LayoutInflater.from(context);
            final View view = inflater.inflate(R.layout.page_list_node, null, false);

            arrowView = (ImageView)view.findViewById(R.id.node_arrow);
            final TextView textView = (TextView)view.findViewById(R.id.node_value);
            textView.setText(value.page.getName());
            textView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Toast.makeText(v.getContext(), value.getPage().getName(), Toast.LENGTH_SHORT).show();
                }
            });

            return view;
        }
    }

This behavior overrides the default when tapping the "textView" portion of the node.
