### ISSUE TITLE
Use With Picasso

### ISSUE THREAD

**Issue by patelakshay13890** [bmelnychuk/AndroidTreeView#5]
How can I use this superb lib. with Picasso for dynamic Image Loading in th App from URL ???
Plz do rply as quick as possible..!!!

**Comment by bmelnychuk** [comment]
Have you tried just use picasso in your implementation of TreeNode.BaseNodeViewHolder (see demo app). Try to use `Picasso.with(context).load("http://i.imgur.com/DvpvklR.png").into(imageView);` in `createNodeView` method.

**Comment by bmelnychuk** [comment]
I don't think this is relevant
