### ISSUE TITLE
How to change Layout Image by Expanding List ?

### ISSUE THREAD

**Issue by mayankneeds** [bmelnychuk/AndroidTreeView#66]
Example :
Before Click

![ice_screenshot_20160331-145830](https://cloud.githubusercontent.com/assets/17738288/14171539/23856f9e-f751-11e5-897d-d1cea27ac7bc.png)

After Click
![ice_screenshot_20160331-145858](https://cloud.githubusercontent.com/assets/17738288/14171559/34983ff0-f751-11e5-9bf1-d457aa43281c.png)

**Comment by bmelnychuk** [comment]
Did you check the sample app? There is a good example with arrow which is different in expanded and collapsed mode

**Comment by mayankneeds** [comment]
Thanks Buddy, I found it !!
just need to add


    public View createNodeView(TreeNode node, IconTreeItem value) {
        final LayoutInflater inflater = LayoutInflater.from(context);
        final View view = inflater.inflate(R.layout.child, null, false);
        img = (ImageView) view.findViewById(R.id.image);
        tvValue = (TextView) view.findViewById(R.id.text);
        img.setImageResource(value.icon);
        tvValue.setText(value.text);
        return view;
    }
    public void toggle(boolean active) {
        img.setImageResource(active ? R.drawable.add_wishlist : R.drawable.inquire_now);
    }

in your Holder class
