### ISSUE TITLE
LongClickListeners

### ISSUE THREAD

**Issue by meetmkjangid** [bmelnychuk/AndroidTreeView#69]
Hi,
Your library is awesome.
Just one thing, on long click, the node opens up by default. How can i disable it.

**Comment by bmelnychuk** [comment]
Use setUseAutoToggle(boolean enableAutoToggle)

**Comment by meetmkjangid** [comment]
Hi,
I am using your library inclusion in adnroid "com.github.bmelnychuk:atv:1.2.+". But I could not find the above said method in it.

**Comment by meetmkjangid** [comment]
In absence of reply, I had to copy paste your code files and do all modifications.
