### ISSUE TITLE
restore state issue

### ISSUE THREAD

**Issue by fahimk** [bmelnychuk/AndroidTreeView#7]
Right now on restoring the code takes the selected nodes and puts them in a hashset

```final Set<String> openNodes = new HashSet<>(Arrays.asList(openNodesArray));```

So if you have 1;0:0;2;0:0 gives you HashSet {1, 0:0, 2}
but if you have 1;0:0;2 that gives you the same HashSet {1, 0:0, 2}

There is data loss here because there is no indication which 0:0 is selected 

To see this in practice go to "Custom Holder Example"
open "My Profile" -> Social
open "Bruce Wayne" -> Social
open "Barry Allen" -> Social; open "Barry Allen" -> Places
rotate the device
All the places nodes are expanded.

I have a solution which looks like this and writes the tree with DFS as a string
```
    private void getSaveState(TreeNode root, StringBuilder sBuilder) {
        for (TreeNode node : root.getChildren()) {
            if (node.isExpanded()) {
                sBuilder.append(NODE_EXPANDED);
            }
            else {
                sBuilder.append(NODE_COLLAPSED);
            }
            getSaveState(node, sBuilder);
        }
    }

    public String getSaveState() {
        final StringBuilder builder = new StringBuilder();
        getSaveState(mRoot, builder);
        return builder.toString();
    }
```
Let me know what you think of this solution, and I'll make a pull request with the changes.

**Comment by bmelnychuk** [comment]
Thank you Fahim! I will take a look on this at weekend.

**Comment by bmelnychuk** [comment]
Your code looks good. But I found small problem in my code: I used `path.append(mId);` (the same id all the time) instead of `path.append(node.getId());` and I think that solved the issue. Let me know if it works for you

**Comment by fahimk** [comment]
Yes, that should fix it too. I didn't see that there was an id property.
