### ISSUE TITLE
Opened child nodes retain their state even if the parent is collapsed

### ISSUE THREAD

**Issue by meetmkjangid** [bmelnychuk/AndroidTreeView#71]
Hi.  Your library is important to our ongoing work requiring a sales model treeview.  Please help me out on this one. Once I open a deep nested child within a node and then I collapse the node itself and reopen it, the child nodes maintain their opened state which is not required in our implementation.

**Comment by meetmkjangid** [comment]
In absence of reply, I had to copy paste your code files and do all modifications. But library is superawesome

**Comment by maxime-kouemo** [comment]
@mkjangid can you please explain how you achieved that?

**Comment by mkjangid** [comment]
@maxime-kouemo The code is itself there but you will have to deep dive in order to enable this which has been less preferred by developer. It will take time.

**Comment by maxime-kouemo** [comment]
I did the same as you did. There was a method for collapse(TreeNode) that called another one with a false parameter. I replaced it with true and that was it.
