### ISSUE TITLE
About Indentation

### ISSUE THREAD

**Issue by anuj1708** [bmelnychuk/AndroidTreeView#76]
Sorry It is not a issue but could not find any contact to ask.
I am trying to use this library but Indentation is not working for me. Can you please tell which part of sample set indentation to ON. And please provide a contact to ask for help.

Thank you.

**Comment by bmelnychuk** [comment]
I did not really understand the problem. Could you give more details?

**Comment by anuj1708** [comment]
No problem .It is solved. Didn't got time lately to tell that. Anyways Thanks a lot :+1:
