### ISSUE TITLE
How to set DefaultViewHolder?

### ISSUE THREAD

**Issue by shuimuqinghua** [bmelnychuk/AndroidTreeView#85]
Hi:
   In my project, I want to use your AndroidTreeView. But my root view and childs have more than two diffent layout. So, i have more than two ViewHolder! In my problem, how can i set the DefaultViewHolder?
   I need your help soon, Thank you!

**Comment by bmelnychuk** [comment]
Hi! If you have different ViewHolders then you can not set it as DefaultViewHolder, instead you can set it per TreeNode: treeNode.setViewHolder(...)
